#ifndef LEVEL_H_
#define LEVEL_H_

#include <stdint.h>

#include "map/Tile.h"

/**
 * The Level object stores and manages the maps for a level.
 *
 * Level maps are generated by passing the Level object itself through one or
 * more Filter objects.
 *
 * @version 1.0
 * @author Travis Veazey
 */
class Level
{
	public:
		/**
		 * Constructor.
		 *
		 * @param width Width of the level.
		 * @param height Height of the level.
		 */
		Level(int width, int height);

		/**
		 * Destructor.
		 */
		~Level();

		/**
		 * Print the level to stdout.
		 */
		void printLevel();

		/**
		 * Get the height of the Level.
		 *
		 * @return The height.
		 */
		int getHeight();

		/**
		 * Get the width of the Level.
		 *
		 * @return The width.
		 */
		int getWidth();

		/**
		 * Retrieve the Tile from the specified x,y coordinates on the map.
		 *
		 * @param x The x coordinate.
		 * @param y The y coordinate.
		 *
		 * @return Reference to the Tile object at that location.
		 */
		Tile& getTile(int x, int y);

		/**
		 * Set the Tile at the specified x,y location to the same type as tile.
		 *
		 * @param x
		 * @param y
		 * @param tile
		 */
		void setTile(int x, int y, Tile tile);

		/**
		 * Proxy class allows access to the Level object's individual Tile
		 * objects via two-dimensional array access.
		 */
		class Proxy
		{
			public:
				/**
				 * Constructor stores a reference to this Level object, as well
				 * as the first-level array index (the x coordinate).
				 *
				 * @param level Level object.
				 * @param x X coordinate we're accessing.
				 */
				Proxy(Level& level, int x);

				/**
				 * Retrieve the Tile object at the specified y coordinate and
				 * the x coordinate that this object is proxying.
				 *
				 * @param y The y coordinate.
				 *
				 * @return The Tile object located here.
				 */
				Tile& operator[](int y);
			private:
				/**
				 * Reference to the proxied Level object.
				 */
				Level& _level;

				/**
				 * X coordinate we're proxying the request to.
				 */
				int _x;
		};
		/**
		 * This and the corresponding Proxy object allow access to the Level
		 * object's map of Tile objects via two-dimensional array access.
		 *
		 * This operator does not permit other operations to be performed on
		 * the retrieved row except to access a particular Tile via the array
		 * access operator.
		 *
		 * @param x The x coordinate for the Tile.
		 *
		 * @return A Proxy object that allows array-style access to the y coordinate.
		 */
		Proxy operator[](int x);
	private:
		/**
		 * Initialize the level to the specified width and height.
		 */
		void initializeLevel();

		/**
		 * This two-dimensional array stores the Tile objects making up the
		 * map.
		 */
		Tile** _tiles;

		/**
		 * Width of the level.
		 */
		int _width;
		/**
		 * Height of the level.
		 */
		int _height;
};

#endif
